# Generated by Django 4.0.2 on 2022-02-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmilanweb', '0002_rename_clubs_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
