# Generated by Django 4.0.2 on 2022-02-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmilanweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clubs',
            new_name='Club',
        ),
    ]
