# Generated by Django 4.0.2 on 2022-02-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmilanweb', '0003_club_year_alter_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_crest',
            field=models.ImageField(blank=True, upload_to='club_crest'),
        ),
        migrations.AddField(
            model_name='club',
            name='colors',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='club',
            name='nickname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='stadium',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='stadium_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='web_site',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
