# Generated by Django 4.0.2 on 2022-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmilanweb', '0004_club_club_crest_club_colors_club_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='stadium',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
